#
### FILE SPECS
#
##############################################################################################
#
# WORKING EXAMPLE yaml
#


clock_timer:
  grow_lights:
    channels:
      - 1
    active_hours: '12:30am - 4:00am'

simple_timer:
  irrigation_pump:
    channels:
      - 10
      - 11
    on_time: 20s
    off_time: 20s

threshold:
  climate_control:
    upper:
      channel: 5
      limit: 20.3
    lower:
      channel: 6
      limit: 19.7
    target: 20
    input: AdafruitDHT1.temperature
    min_duty_cycle: 0.2
    alter_target:
      #input: AdafruitDHT1.humidity
      output: simple_timer.irrigation_pump
      alter_by: -5
      #when: "> 18"
      when: activated

#  reservoir_ph_adjuster:
#    upper:
#      channel: 2
#      limit: 6
#    lower:
#      channel: 3
#      limit: 5
#    target: 5.5
#    input: ReservoirPH1.ph_level
#    periodic:
#      active: 10s
#      inactive: 30m

triggered:
  reservoir_air_pump:
    channels:
      - 15
    object: simple_timer.irrigation_pump
    before: 5s
    after: 5s

sensors:
  AdafruitDHT1:
    type: DHT11
    channel: 3  # tested with adafruit DHT11 temp/humi sensor
    provides:
      - humidity
      - temperature

  AdafruitDHT2:
    type: DHT22
    channel: 4  # tested with adafruit DHT22 temp/humi sensor
    provides:
      - humidity
      - temperature
    power_channel: 27

  ambient1:
    type: DS18B20
    sensor_id: 28-041752029bff  # tested with duinotech temp sensor

  ReservoirPH1:  # completely untested
    type: foo
    channel: 7
    provides:
      - ph_level

  BloomTank1:
    type: HC-SR04
    channels:  # tested with duinotech ultrasonic sensor
      out: 20  # TRIG
      in: 21  # ECHO
    samples: 5
    correction: ambient1
    value_processor:
      range_percentage:
        min: 20
        max: 100
        inverted: true

